### ISSUE TITLE
PA Review: Search

### ISSUE THREAD

**Issue by tsai810417** [tsai810417/FreshCards#11]
- [x] Backend: controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by tsai810417** [comment]
search section is ready for review

**Comment by wongshington** [comment]
- [x] can't search decks back to back, it gets stuck in a loading screen

**Comment by wongshington** [comment]
looks good
