### ISSUE TITLE
PA Review: Study Deck 

### ISSUE THREAD

**Issue by tsai810417** [tsai810417/FreshCards#13]
- [x] Backend: DB, model, controller, views
 - [x] Redux Loop: ajax, actions, reducer
 - [x] Presentational Components
 - [ ] Styling
 - [x] Smooth, bug-free navigation
 - [ ] Adequate and appropriate seeds
 - [x] logged in user can study decks
 - [x] store the user's progress of the deck

**Comment by tsai810417** [comment]
study deck section is ready for review

**Comment by wongshington** [comment]
- [x] specify that the "mastery" score is for the deck when presenting it
- [x] cards should be a bit bigger on the study deck pages
- [ ] more lively colors on the rest of the site, not just nav bar
- [x] maybe center deck title when reviewing cards
- if i submit a super long question/answer 
   - [x] shouldn't block the left and right card buttons
   - [x] should either have a limit for the length of the question/answer or should expand the size of the card at least a little bigger

**Comment by tsai810417** [comment]
updated the styling and seeding

**Comment by wongshington** [comment]
- [ ] on the deck show page it would be good to show the deck mastery somewhere as well
- [ ] will need to style the question/answers table a little more
- [ ] set a minimum width on the cards while studying so they don't squish down too much if you resize the window
- [ ] model your deck index more closely to the site, they use different colors for the divs, different text colors, different text sizes, etc.

![screen shot 2018-04-13 at 11 36 38 am](https://user-images.githubusercontent.com/26219652/38752159-1c320f60-3f0f-11e8-80cb-fcbf2605d6e4.png)
