### ISSUE TITLE
Auth MVP check

### ISSUE THREAD

**Issue by tsai810417** [tsai810417/FreshCards#8]
- [x] user can sign up, login, logout
- [x] create demo login for testing the site
- [x] style the buttons and SessionFormContainer

**Comment by wongshington** [comment]
- [x] remove all debuggers from code that you push up to heroku
- [x] change form font color to black
- [x] center bottom text "Already had an account? or try demo login?Log In"
     - "Already have an account? Login here or try a Demo Login.

**Comment by wongshington** [comment]
- [x] css on the login and sign up buttons, if i make the screen even a little bit smaller the buttons get chopped

**Comment by wongshington** [comment]
everything looks good. great home page!
