### ISSUE TITLE
PA review: Deck

### ISSUE THREAD

**Issue by tsai810417** [tsai810417/FreshCards#9]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by tsai810417** [comment]
deck section completed ready for review.

**Comment by wongshington** [comment]
- [x] renders errors on deck form page
